= Beibehaltung der Ordnerhierarchie
:allow-uri-read: 




=== Beibehaltung der Ordnerhierarchie

Standardmäßig behält Disaster Recovery die VM-Inventarhierarchie (Ordnerstruktur) beim Failover bei.  Falls das Wiederherstellungsziel den erforderlichen Ordner nicht enthält, wird dieser von Disaster Recovery erstellt.

Sie können diese Einstellung nun überschreiben, indem Sie einen neuen übergeordneten VM-Ordner festlegen oder die Option **Ursprüngliche Ordnerhierarchie beibehalten** deaktivieren.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.adoc["Erstellen eines Replikationsplans"].



=== Optimierte Aktualisierung des Konsolenagenten

Die Disaster-Recovery-Lösung unterstützt nun einen optimierten Prozess für die Verwendung mehrerer Console-Agenten in einer Arbeitsumgebung.  Um zwischen verschiedenen Console-Agenten zu wechseln, müssen Sie Ihre vCenter-Konfiguration bearbeiten, die Anmeldeinformationen neu ermitteln und die Replikationspläne aktualisieren, um den neuen Console-Agenten zu verwenden.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/reference/switch-console-agents.html["Switch Console-Agenten"].
