= Google Cloud VMware Engine (GCVE) wird ab sofort allgemein unterstützt (GA)
:allow-uri-read: 




[[google-cloud-vmware-engine-gcve-support-is-now-generally-available-ga]]
=== Google Cloud VMware Engine (GCVE) wird ab sofort allgemein unterstützt (GA)

NetApp Disaster Recovery-Unterstützung für GCVE ist jetzt allgemein verfügbar (GA). Mit GA-Unterstützung unterstützt Disaster Recovery für GCVE jetzt:

* *Plattformverwaltete Snapshots:* Backups und Aufbewahrungsrichtlinien lassen sich nahtlos über ONTAP oder Google Cloud Platform (GCP) verwalten.
* *Mehrere Datenspeicher pro Replikationsplan:* Vereinfachen Sie Ihre Disaster Recovery-Pläne, indem Sie mehrere Datenspeicher in einer einzigen Replikationsstrategie konsolidieren.
* *Erzwingen eines Failovers bei nicht verfügbaren Quellstandorten:* Wechseln Sie zu einem Disaster Recovery-Standort, wenn die Quelle nicht verfügbar ist.
* *Neusynchronisierung von SnapMirror verzögern und Replikation bei Bedarf wiederherstellen:* SnapMirror-Neusynchronisierungen können mithilfe der Option "skip protect" verzögert werden, um Auswirkungen auf Produktionsworkloads während Spitzenzeiten zu vermeiden. Die Replikation lässt sich später bei Bedarf mit der Option "re-protect" wiederherstellen.


Weitere Informationen zur Unterstützung von GCVE finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/release-notes/dr-limitations.html["Unterstützte Konfigurationen für die Notfallwiederherstellung"^].
