= Einen Datenspeicher von Replikationsplänen ausschließen
:allow-uri-read: 




[[exclude-a-datastore-from-replication-plans]]
=== Einen Datenspeicher von Replikationsplänen ausschließen

Beim Erstellen eines Replikationsplans in Disaster Recovery können nun bestimmte Datenspeicher von der Replikation ausgeschlossen werden. In Situationen, in denen eine VM für die Verwendung mehrerer Datenspeicher konfiguriert ist, lässt sich damit einschränken, welche Datenspeicher repliziert werden.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["Erstellen eines Replikationsplans"^].



[[removed-password-validation-from-vcenter-password]]
=== Passwortvalidierung aus vCenter-Passwort entfernt

Die Notfallwiederherstellung hat die Passwortbeschränkungen für vCenter-Passwörter aufgehoben, sodass Passwörter Leerzeichen enthalten dürfen.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/reference/evs-deploy-guide-add-vcenters.html["Hinzufügen von lokalen und Amazon EVS vCenter-Clustern in NetApp Disaster Recovery"^].



[[new-replication-plan-submenu]]
=== Neues Untermenü für Replikationsplan

Die Notfallwiederherstellung bietet jetzt neue Menüoptionen, um vCenter-Aktualisierungen über das Replikationsplan-Dashboard auszulösen. Das Untermenü ist über das Aktionsmenü des Replikationsplan-Dashboards zugänglich: Zuerst **Plan Health** und dann **Refresh Source vCenter / Refresh Target vCenter** auswählen.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html#modify-a-replication-plan["Einen Replikationsplan ändern"^].



[[improved-network-discovery]]
=== Verbesserte Netzwerkerkennung

Disaster Recovery umfasst nun eine verbesserte Netzwerkerkennung, um ein breiteres Spektrum an Netzwerkkonfigurationen zu unterstützen.
