---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: Einführung von NetApp Disaster Recovery mit Amazon EVS und Amazon FSx for NetApp ONTAP. 
---
= Informationen zu NetApp Disaster Recovery mit Amazon Elastic VMware Service und Amazon FSx for NetApp ONTAP
:allow-uri-read: 


[role="lead"]
NetApp Disaster Recovery unterstützt den Schutz von VMware-Workloads, indem Daten aus lokalen Umgebungen zur Notfallwiederherstellung nach Amazon EVS und Amazon FSx for NetApp ONTAP repliziert werden.

Eine der größten Herausforderungen bei jeder DR-Lösung besteht darin, die zusätzlichen Kosten für den Kauf, die Konfiguration und die Wartung zusätzlicher Rechen-, Netzwerk- und Speicherressourcen zu bewältigen, nur um eine DR-Replikations- und Wiederherstellungsinfrastruktur bereitzustellen.  Eine beliebte Option zum Schutz kritischer virtueller Ressourcen vor Ort ist die Verwendung in der Cloud gehosteter virtueller Ressourcen als DR-Replikations- und Wiederherstellungsinfrastruktur.  Amazon ist ein Beispiel für eine solche Lösung, die kostengünstige Ressourcen bereitstellen kann, die mit von NetApp ONTAP gehosteten VM-Infrastrukturen kompatibel sind.

Amazon hat seinen Amazon Elastic VMware Service (Amazon EVS) eingeführt, der VMware Cloud Foundation in Ihrer virtuellen privaten Cloud (VPC) ermöglicht. Amazon EVS bietet die Ausfallsicherheit und Leistung von AWS zusammen mit der gewohnten VMware Software und Tools, sodass Amazon EVS vCenters in Ihre lokale virtualisierte Infrastruktur integriert werden können.

Während Amazon EVS mit integrierten Speicherressourcen geliefert wird, kann die Nutzung von nativem Speicher die Effektivität für Unternehmen mit speicherintensiven Workloads verringern. In diesen Fällen kann die Kombination von Amazon EVS mit Amazon FSx for NetApp ONTAP Storage (Amazon FSxN) eine flexiblere Speicherlösung bieten. Zudem bietet die Nutzung von NetApp ONTAP Storage-Lösungen vor Ort zur Bereitstellung Ihrer VMware-Infrastruktur in Verbindung mit Amazon EVS und FSx for ONTAP Funktionen für Interoperabilität und Datenschutz zwischen lokalen und Cloud-Umgebungen.

Informationen zu Amazon FSx for NetApp ONTAP finden Sie unter https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Erste Schritte mit Amazon FSx for NetApp ONTAP"^] .
