---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-config-prereqs.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Sie sollten sicherstellen, dass mehrere Voraussetzungen erfüllt sind, bevor Sie mit der Konfiguration von Amazon EVS mit NetApp Disaster Recovery fortfahren. 
---
= Voraussetzungen für Amazon EVS mit NetApp Disaster Recovery
:allow-uri-read: 


[role="lead"]
Sie sollten sicherstellen, dass mehrere Voraussetzungen erfüllt sind, bevor Sie mit der Konfiguration von Amazon EVS mit NetApp Disaster Recovery fortfahren.

Gehen Sie insbesondere wie folgt vor:

* Erstellen Sie ein vCenter-Benutzerkonto mit den spezifischen VMware-Berechtigungen, die für NetApp Disaster Recovery erforderlich sind, um die erforderlichen Vorgänge auszuführen.
+

NOTE: Wir empfehlen nicht, das standardmäßige Administratorkonto „\administrator@vsphere.com“ zu verwenden.  Stattdessen sollten Sie auf allen vCenter-Clustern, die am DR-Prozess teilnehmen, ein NetApp Disaster Recovery spezifisches Benutzerkonto erstellen.  Eine Liste der erforderlichen Berechtigungen finden Sie unterlink:vcenter-privileges.html["Für NetApp Disaster Recovery erforderliche vCenter-Berechtigungen"] .

* Stellen Sie sicher, dass sich alle vCenter-Datenspeicher, die durch NetApp Disaster Recovery geschützte VMs hosten, auf NetApp ONTAP -Speicherressourcen befinden.
+
Der Dienst unterstützt NFS und VMFS auf iSCSI (und nicht FC) bei Verwendung von Amazon FSx auf NetApp ONTAP.  Während der Dienst FC unterstützt, ist dies bei Amazon FSx for NetApp ONTAP nicht der Fall.

* Stellen Sie sicher, dass Ihr Amazon EVS vCenter mit einem Amazon FSx for NetApp ONTAP Speichercluster verbunden ist.
* Stellen Sie sicher, dass auf allen geschützten VMs VMware-Tools installiert sind.
* Stellen Sie sicher, dass Ihr lokales Netzwerk über eine von Amazon genehmigte Verbindungsmethode mit Ihrem AWS VPC-Netzwerk verbunden ist.  Wir empfehlen Ihnen, AWS Direct Connect, AWS Private Link oder ein AWS Site-to-Site-VPN zu verwenden.

