---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: Einführung von NetApp Disaster Recovery mit Amazon EVS und Amazon FSx for NetApp ONTAP. 
---
= Einführung von NetApp Disaster Recovery mit Amazon Elastic VMware Service und Amazon FSx for NetApp ONTAP
:allow-uri-read: 


[role="lead"]
Kunden sind für Produktions-Rechenlasten zunehmend auf virtualisierte Infrastrukturen angewiesen, beispielsweise auf Basis von VMware vSphere.  Da diese virtuellen Maschinen (VMs) für ihre Unternehmen immer wichtiger geworden sind, müssen Kunden diese VMs vor denselben Katastrophen schützen wie ihre physischen Rechenressourcen.  Die derzeit angebotenen Disaster Recovery (DR)-Lösungen sind komplex, teuer und ressourcenintensiv.  NetApp, der größte Speicheranbieter für virtualisierte Infrastrukturen, hat ein begründetes Interesse daran, sicherzustellen, dass die VMs seiner Kunden auf die gleiche Weise geschützt sind, wie wir auf ONTAP -Speicher gehostete Daten aller Art schützen.  Um dieses Ziel zu erreichen, hat NetApp den NetApp Disaster Recovery-Dienst entwickelt.

Eine der größten Herausforderungen bei jeder DR-Lösung besteht darin, die zusätzlichen Kosten für den Kauf, die Konfiguration und die Wartung zusätzlicher Rechen-, Netzwerk- und Speicherressourcen zu bewältigen, nur um eine DR-Replikations- und Wiederherstellungsinfrastruktur bereitzustellen.  Eine beliebte Option zum Schutz kritischer virtueller Ressourcen vor Ort ist die Verwendung in der Cloud gehosteter virtueller Ressourcen als DR-Replikations- und Wiederherstellungsinfrastruktur.  Amazon ist ein Beispiel für eine solche Lösung, die kostengünstige Ressourcen bereitstellen kann, die mit von NetApp ONTAP gehosteten VM-Infrastrukturen kompatibel sind.

Amazon hat seinen Amazon Elastic VMware Service (Amazon EVS) eingeführt, der VMware Cloud Foundation in Ihrer Virtual Private Cloud (VPC) ermöglicht.  Amazon EVS bietet die Ausfallsicherheit und Leistung von AWS zusammen mit der vertrauten VMware-Software und -Tools, sodass Amazon EVS vCenters als Erweiterung Ihrer virtualisierten Infrastruktur vor Ort integriert werden können.

Obwohl Amazon EVS über integrierte Speicherressourcen verfügt, kann die Verwendung von nativem Speicher die Effektivität für Organisationen mit speicherintensiven Arbeitslasten verringern.  In diesen Fällen kann die Kombination von Amazon EVS mit Amazon FSx for NetApp ONTAP -Speicher (Amazon FSxN) eine flexiblere Speicherlösung bieten.  Wenn Sie NetApp ONTAP -Speicherlösungen vor Ort zum Hosten Ihrer VMware-Infrastruktur verwenden, erhalten Sie durch die Verwendung von Amazon EVS mit FSx für ONTAP außerdem erstklassige Dateninteroperabilitäts- und Schutzfunktionen zwischen Ihren lokalen und in der Cloud gehosteten Infrastrukturen.

Informationen zu Amazon FSx for NetApp ONTAP finden Sie unter https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Erste Schritte mit Amazon FSx for NetApp ONTAP"^] .
