---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-enable-draas.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter,amazon elastic vmware service 
summary: Einführung von NetApp Disaster Recovery mit Amazon EVS und Amazon FSx for NetApp ONTAP.  NetApp Disaster Recovery ist ein lizenziertes Produktangebot, das vor der Verwendung erworben werden muss.  Es gibt verschiedene Arten von Lizenzen und verschiedene Möglichkeiten, Lizenzen zu erwerben. 
---
= Fügen Sie Ihrem NetApp Console für Amazon EVS den NetApp Disaster Recovery -Dienst hinzu
:allow-uri-read: 


[role="lead"]
NetApp Disaster Recovery ist ein lizenziertes Produktangebot, das vor der Verwendung erworben werden muss.  Es gibt verschiedene Arten von Lizenzen und verschiedene Möglichkeiten, Lizenzen zu erwerben.  Eine Lizenz berechtigt Sie zum Schutz einer bestimmten Datenmenge für einen bestimmten Zeitraum.

Weitere Informationen zu NetApp Disaster Recovery Lizenzen finden Sie unterlink:../get-started/dr-licensing.html["Einrichten der Lizenzierung für NetApp Disaster Recovery"] .



== Lizenztypen

Es gibt zwei primäre Lizenztypen:

* NetApp bietet einelink:../get-started/dr-licensing.html["30-Tage-Testlizenz"] mit dem Sie NetApp Disaster Recovery unter Verwendung Ihrer ONTAP und VMware-Ressourcen evaluieren können.  Diese Lizenz ermöglicht eine 30-tägige Nutzung einer unbegrenzten Menge an geschützter Kapazität.
* Erwerben Sie eine Produktionslizenz, wenn Sie DR-Schutz über den 30-tägigen Testzeitraum hinaus wünschen.  Diese Lizenz kann über die Marktplätze aller Cloud-Partner von NetApp erworben werden. Für diesen Leitfaden empfehlen wir jedoch, dass Sie Ihre Marktplatzlizenz für NetApp Disaster Recovery über den Amazon AWS Marketplace erwerben.  Weitere Informationen zum Erwerb einer Lizenz über den Amazon Marketplace finden Sie unterlink:../get-started/dr-licensing.html["Abonnieren Sie über AWS Marketplace"] .




== Bemessen Sie Ihren Kapazitätsbedarf für die Notfallwiederherstellung

Bevor Sie Ihre Lizenz erwerben, sollten Sie wissen, wie viel ONTAP Speicherkapazität Sie schützen müssen.  Einer der Vorteile der Verwendung von NetApp ONTAP Speicher ist die hohe Effizienz, mit der NetApp Ihre Daten speichert.  Alle in einem ONTAP Volume gespeicherten Daten – beispielsweise VMware-Datenspeicher, die VMs hosten – werden auf hocheffiziente Weise gespeichert.  ONTAP verwendet beim Schreiben von Daten in den physischen Speicher standardmäßig drei Arten der Speichereffizienz: Komprimierung, Deduplizierung und Komprimierung.  Das Nettoergebnis ist eine Speichereffizienz zwischen 1,5:1 und 4:1, abhängig von den gespeicherten Datentypen.  Tatsächlich bietet NetApp eine https://www.netapp.com/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf["Speichereffizienzgarantie"^] für bestimmte Arbeitslasten.

Dies kann für Sie von Vorteil sein, da NetApp Disaster Recovery die Kapazität für Lizenzierungszwecke berechnet, nachdem alle ONTAP Speichereffizienzen angewendet wurden.  Nehmen wir beispielsweise an, Sie haben in vCenter einen 100 Terabyte (TiB) großen NFS-Datenspeicher bereitgestellt, um 100 VMs zu hosten, die Sie mithilfe des Dienstes schützen möchten.  Nehmen wir außerdem an, dass beim Schreiben der Daten auf das ONTAP Volume automatisch angewendete Techniken zur Speichereffizienz dazu führen, dass diese VMs nur 33 TiB verbrauchen (Speichereffizienz 3:1).  NetApp Disaster Recovery muss nur für 33 TiB lizenziert werden, nicht für 100 TiB.  Dies kann im Vergleich zu anderen DR-Lösungen einen sehr großen Vorteil hinsichtlich der Gesamtbetriebskosten Ihrer DR-Lösung bedeuten.

.Schritte
. Um zu ermitteln, wie viele Daten auf jedem Volume verbraucht werden, auf dem sich ein zu schützender VMware-Datenspeicher befindet, ermitteln Sie den Kapazitätsverbrauch auf der Festplatte, indem Sie für jedes Volume den ONTAP CLI-Befehl ausführen: `volume show-space -volume < _volume name_ > -vserver < _SVM name_ >` .
+
Beispiel:

+
[listing]
----
cluster1::> volume show-space
Vserver : vm-nfs-ds1
Volume  : vol0
Feature                                Used      Used%
-----------------------------      --------     ------
User Data                           163.4MB         3%
Filesystem Metadata                   172KB         0%
Inodes                               2.93MB         0%
Snapshot Reserve                    292.9MB         5%
Total Metadata                        185KB         0%
Total Used                          459.4MB         8%
Total Physical Used                 166.4MB         3%

----
. Notieren Sie den Wert *Total Physical Used* für jedes Volume.  Dies ist die Datenmenge, die NetApp Disaster Recovery schützen muss. Anhand dieses Werts bestimmen Sie, wie viel Kapazität Sie lizenzieren müssen.

