---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-install-connector.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Einführung von NetApp Disaster Recovery mit Amazon EVS und Amazon FSx for NetApp ONTAP.  Obwohl der Connector an jedem Ihrer Netzwerkstandorte installiert werden kann, empfehlen wir für die NetApp Disaster Recovery, den Connector am DR-Standort zu installieren.  Dadurch wird sichergestellt, dass im Falle eines Ausfalls des primären Standorts die NetApp Konsolen-Benutzeroberfläche weiterhin Kontakt mit dem Konsolenagenten hat und den Wiederherstellungsprozess innerhalb dieses DR-Standorts orchestrieren kann. 
---
= Installieren Sie den NetApp Console -Agenten für NetApp Disaster Recovery
:allow-uri-read: 


[role="lead"]
Ein NetApp Console Agent ist eine NetApp -Software, die in Ihrer Cloud oder Ihrem lokalen Netzwerk ausgeführt wird.  Es führt die Aktionen aus, die die NetApp Console zur Verwaltung Ihrer Dateninfrastruktur ausführen muss.  Der Konsolenagent fragt die NetApp Disaster Recovery -Software als Serviceebene ständig nach erforderlichen Aktionen ab.

Bei NetApp Disaster Recovery werden mit den ausgeführten Aktionen VMware vCenter-Cluster und ONTAP Speicherinstanzen mithilfe nativer APIs für jeden jeweiligen Dienst orchestriert, um Schutz für Produktions-VMs zu bieten, die an einem lokalen Standort ausgeführt werden.  Obwohl der Konsolenagent an jedem Ihrer Netzwerkstandorte installiert werden kann, empfehlen wir für NetApp Disaster Recovery, den Konsolenagenten am DR-Standort zu installieren.  Dadurch wird sichergestellt, dass im Falle eines Ausfalls des primären Standorts die Cloud-basierte Konsolen-Benutzeroberfläche von NetApp weiterhin Kontakt mit dem Konsolenagenten hat und den Wiederherstellungsprozess innerhalb dieses DR-Standorts orchestrieren kann.

Um den Dienst zu verwenden, installieren Sie den Konsolenagenten im Standardmodus.  Weitere Informationen zu den verschiedenen Konsolen-Agent-Installationsarten finden Sie unter https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Erfahren Sie mehr über die Bereitstellungsmodi der NetApp Console | NetApp Dokumentation"^] .

Obwohl der Konsolenagent für die Verwendung des Dienstes von entscheidender Bedeutung ist, hängen die Installationsschritte zur Installation des Konsolenagenten von Ihren Anforderungen und der Netzwerkkonfiguration ab.  Es geht über den Rahmen dieser Informationen hinaus, spezifische Anweisungen zur Installation bereitzustellen.

Die einfachste Methode zum Installieren des Konsolenagenten mit Amazon AWS ist die Verwendung des AWS Marketplace.  Weitere Informationen zur Installation des Konsolenagenten über den AWS Marketplace finden Sie unter https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-marketplace.html["Erstellen Sie einen Konsolenagenten aus dem AWS Marketplace | NetApp Dokumentation"^] .
