---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-install-connector.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Der NetApp Console-Agent orchestriert die Verbindung und Verwaltung zwischen der NetApp Console und Cloud- oder On-Prem-Speicherressourcen. 
---
= Installieren Sie den NetApp Console -Agenten für NetApp Disaster Recovery
:allow-uri-read: 


[role="lead"]
Ein NetApp Console-Agent ermöglicht es Ihnen, Ihre NetApp Console-Bereitstellungen mit Ihrer Infrastruktur zu verbinden, um Lösungen sicher über AWS, Azure, Google Cloud oder lokale Umgebungen hinweg zu orchestrieren. Der Console-Agent führt die Aktionen aus, die die NetApp Console zur Verwaltung Ihrer Dateninfrastruktur ausführen muss. Der Console-Agent fragt die NetApp Disaster Recovery Software-as-a-Service-Schicht kontinuierlich ab, um alle erforderlichen Aktionen auszuführen.

Für Disaster Recovery orchestrieren diese Aktionen VMware vCenter Cluster und ONTAP Speicherinstanzen mithilfe der nativen APIs der jeweiligen Dienste, um Schutz für produktive VMs bereitzustellen, die an einem lokalen Standort ausgeführt werden. Obwohl der Console Agent an jedem Ihrer Netzwerstandorte installiert werden kann, wird empfohlen, den Console Agent für Disaster Recovery am Disaster Recovery Standort zu installieren. Die Installation am Disaster Recovery Standort stellt sicher, dass im Falle eines Ausfalls des primären Standorts die NetApp Console UI die Verbindung zum Console Agent aufrechterhält und den Wiederherstellungsprozess innerhalb dieses Disaster Recovery Standorts orchestrieren kann.



[[installation]]
== Installation

* Um NetApp Disaster Recovery zu nutzen, installieren Sie den Console-Agenten im Standardmodus. Weitere Informationen zu den Typen der Console-Agenten-Installationen finden Sie unter https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Erfahren Sie mehr über die Bereitstellungsmodi der NetApp Console"^].


Die konkreten Installationsschritte für den Konsolenagenten hängen von Ihrem Bereitstellungstyp ab. Siehe link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["Erfahren Sie mehr über Konsolenagenten"^] für weitere Informationen.


TIP: Die einfachste Methode zur Installation des Console-Agenten mit Amazon AWS ist die Verwendung des AWS Marketplace. Weitere Informationen zur Installation des Console-Agenten über den AWS Marketplace finden Sie unter  https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-marketplace.html["Erstellen Sie einen Console-Agenten aus dem AWS Marketplace"^].
