---
sidebar: sidebar 
permalink: use/monitor-jobs.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, monitor, bluexp 
summary: NetApp Disaster Recovery ist ein Cloud-basierter Disaster-Recovery-Dienst, der Disaster-Recovery-Workflows automatisiert.  Sie können alle Disaster-Recovery-Jobs überwachen und ihren Fortschritt bestimmen. 
---
= Überwachen Sie NetApp Disaster Recovery -Jobs
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Sie können alle NetApp Disaster Recovery -Jobs überwachen und ihren Fortschritt bestimmen.



[[view-jobs]]
== Jobs anzeigen

*Erforderliche NetApp Console-Rolle* Die Rolle Superadmin, Disaster recovery admin, Disaster recovery application admin oder Disaster recovery viewer ist erforderlich, um diese Aufgabe auszuführen. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Erfahren Sie mehr über Benutzerrollen und Berechtigungen in NetApp Disaster Recovery"^]. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^].

.Schritte
. Melden Sie sich an bei https://console.netapp.com/["NetApp Console"^] .
. Wählen Sie in der linken Navigation der NetApp Console *Schutz* > *Notfallwiederherstellung*.
. Wählen Sie im Menü *Jobüberwachung* aus.
. Erkunden Sie alle betriebsbezogenen Jobs und überprüfen Sie deren Zeitstempel und Status.
. Um Details zu einem bestimmten Job anzuzeigen, die entsprechende Zeile auswählen. Jobdetails können zur Offline-Ansicht heruntergeladen werden, indem im Aktionsmenü **Jobdetails herunterladen** ausgewählt wird.
+

TIP: Bei der Überprüfung der Auftragsdetails zeigt Disaster Recovery den Benutzer an, der den Auftrag initiiert hat. Wenn als Verantwortlicher „system“ aufgeführt ist, bedeutet dies, dass Disaster Recovery den Auftrag initiiert hat.

. Um die Informationen zu aktualisieren, wählen Sie *Aktualisieren*.




[[cancel-a-job]]
== Abbrechen eines Auftrags

Sie können einen laufenden oder in der Warteschlange befindlichen Auftrag abbrechen, wenn er festhängt oder um einen ausstehenden Vorgang zu priorisieren.

*Erforderliche NetApp Console-Rolle* Zur Ausführung dieser Aufgabe ist die Rolle des Super-Admins, Disaster recovery Admins, Disaster recovery Failover Admins oder Disaster recovery Application Admins erforderlich. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Erfahren Sie mehr über Benutzerrollen und Berechtigungen in NetApp Disaster Recovery"^]. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^].

.Schritte
. Wählen Sie in der linken Navigationsleiste der NetApp Console *Schutz* > *Notfallwiederherstellung*.
. Wählen Sie im Menü *Jobüberwachung* aus.
. Notieren Sie auf der Job-Monitor-Seite die ID des Jobs, den Sie abbrechen möchten.
+
Der Auftrag muss sich im Status „In Bearbeitung“ oder „In der Warteschlange“ befinden.

. Im Aktionsmenü die Option **Auftrag abbrechen** auswählen.

