---
sidebar: sidebar 
permalink: use/monitor-jobs.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, monitor, bluexp 
summary: NetApp Disaster Recovery ist ein Cloud-basierter Disaster-Recovery-Dienst, der Disaster-Recovery-Workflows automatisiert.  Sie können alle Disaster-Recovery-Jobs überwachen und ihren Fortschritt bestimmen. 
---
= Überwachen Sie NetApp Disaster Recovery -Jobs
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Überwachung von NetApp Disaster Recovery Jobs ermöglicht die Einsicht in deren Verlauf, Status und Details. Das Nachverfolgen von Auftragsstatus und Fortschritt ermöglicht das Erkennen fehlgeschlagener oder blockierter Vorgänge, bevor diese die Wiederherstellungsbereitschaft beeinträchtigen.



[[view-jobs]]
== Jobs anzeigen

*Erforderliche NetApp Console-Rolle* Die Rolle Superadmin, Disaster recovery admin, Disaster recovery application admin oder Disaster recovery viewer ist erforderlich, um diese Aufgabe auszuführen. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Erfahren Sie mehr über Benutzerrollen und Berechtigungen in NetApp Disaster Recovery"^]. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^].

.Schritte
. Melden Sie sich an bei https://console.netapp.com/["NetApp Console"^] .
. Wählen Sie in der linken Navigation der NetApp Console *Schutz* > *Notfallwiederherstellung*.
. Wählen Sie im Menü *Jobüberwachung* aus.
. Aufträge, einschließlich ihrer Zeitstempel und ihres Status, können überprüft werden.
. Details zu einem Auftrag werden angezeigt, wenn die entsprechende Zeile ausgewählt wird. Für das Herunterladen von Auftragsdetails zur Offline-Ansicht ist das Aktionsmenü zu öffnen und anschließend **Auftragsdetails herunterladen** auszuwählen.
+

TIP: Bei der Überprüfung der Auftragsdetails zeigt Disaster Recovery den Benutzer an, der den Auftrag initiiert hat. Wenn als Verantwortlicher „system“ aufgeführt ist, hat Disaster Recovery den Auftrag initiiert.

. Um die Informationen zu aktualisieren, wählen Sie *Aktualisieren*.




[[cancel-a-job]]
== Abbrechen eines Auftrags

Sie können einen laufenden oder in der Warteschlange befindlichen Auftrag abbrechen, wenn er festhängt oder um einen ausstehenden Vorgang zu priorisieren.

*Erforderliche NetApp Console-Rolle* Zur Ausführung dieser Aufgabe ist die Rolle des Super-Admins, Disaster recovery Admins, Disaster recovery Failover Admins oder Disaster recovery Application Admins erforderlich. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Erfahren Sie mehr über Benutzerrollen und Berechtigungen in NetApp Disaster Recovery"^]. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^].

.Schritte
. Wählen Sie in der linken Navigationsleiste der NetApp Console *Schutz* > *Notfallwiederherstellung*.
. Wählen Sie im Menü *Jobüberwachung* aus.
. Auf der Seite „Auftragsüberwachung“ ist die ID des Auftrags zu beachten, den Sie abbrechen möchten.
+
Der Auftrag muss sich im Status „In Bearbeitung“ oder „In der Warteschlange“ befinden.

. Im Aktionsmenü die Option **Auftrag abbrechen** auswählen.

