---
sidebar: sidebar 
permalink: get-started/dr-prerequisites.html 
keywords: what are disaster recovery requirements, disaster recovery prerequisites, bluexp, disaster recovery 
summary: Bevor Sie NetApp Disaster Recovery verwenden, stellen Sie sicher, dass Ihre Umgebung die Anforderungen an ONTAP -Speicher, VMware vCenter-Cluster und NetApp Console erfüllt. 
---
= Voraussetzungen für NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Bevor Sie NetApp Disaster Recovery verwenden, stellen Sie sicher, dass Ihre Umgebung die Anforderungen an ONTAP -Speicher, VMware vCenter-Cluster und NetApp Console erfüllt.



== Softwareversionen

[cols="35,55a"]
|===
| Komponente | Mindestversion 


| Amazon FSx for NetApp ONTAP  a| 
Neuste verfügbare Version



| Google Cloud VMware Engine mit Google Cloud NetApp Volumes  a| 
Neuste verfügbare Version



| ONTAP Software  a| 
ONTAP 9.10.0 oder höher



| VMware Cloud für AWS  a| 
Neuste verfügbare Version



| VMware vCenter vor Ort  a| 
7.0u3 oder höher

|===


== Voraussetzungen und Überlegungen für Google Cloud

Bei der Notfallwiederherstellung auf Google Cloud VMware Engine mit Google Cloud NetApp Volumes müssen Sie sicherstellen, dass Sie die richtigen Berechtigungen konfigurieren und die genannten Hinweise beachten.

* Wenden Sie sich an das Google SRE-Team, um die folgenden Dienste auf die Whitelist setzen zu lassen:
+
** Synchronisierungs-API zum Übertragen von Snapshots vom lokalen Speicher in Google Cloud NetApp Volumes.
** Das Google-Projekt mit der VMware-Engine zum Erstellen, Einbinden und Ausbinden von Datenspeichern.


* Du musstlink:https://docs.google.com/forms/d/1zuaHu437MNpUf8i5oByK-OTLWXcNIg0es9t036riYRc/viewform?edit_requested=true["Stellen Sie einen Antrag, um Ihre Volumes für die Hybridreplikation auf die Zulassungsliste setzen zu lassen."^] Die
* Seien Sie sich der folgenden Punkte bewusst:link:https://docs.cloud.google.com/netapp/volumes/docs/quotas["Google Cloud NetApp Volumes Kontingente und Limits"^] Die
* Einem Replikationsplan kann nur ein Volume oder Datenspeicher hinzugefügt werden.
* Überprüfen Sie dielink:../release-notes/dr-limitations.html#limitations-with-google-cloud-netapp-volumes["Einschränkungen"] Die


**Überlegungen zum Ausfallmanagement**

* Failover wird nur mit dem neuesten Snapshot unterstützt. Falls erforderlich, können Sie während des Failovers einen neuen Snapshot erstellen (das heißt, die Option für selektive Snapshots muss deaktiviert sein).
* Nach einem Failover kann kein neuer Snapshot erstellt werden.
* Snapshots können nach einem Failover nicht beibehalten und abgeglichen werden.


**Ausfallüberlegungen**

* Ein Failback ist nur mit der Option „Selektiver Snapshot“ möglich.  Ein Failback kann nicht durch Erstellen eines neuen Snapshots durchgeführt werden.
* Wenn Sie das Cluster-Peering zwischen lokalem Speicher und Google Cloud NetApp Volumes -Speicherclustern entfernen, müssen Sie den Cluster- und Speicher-VM-Peering-Eintrag im lokalen Cluster manuell löschen. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/ontap-cli/vserver-peer-delete.html["Eine vServer-Peer-Beziehung löschen"^].




=== Google Cloud-Berechtigungen

Dem Dienstprinzipal in Google Cloud sollten die folgenden Rollen oder gleichwertige Berechtigungen zugewiesen werden:

* link:https://docs.cloud.google.com/compute/docs/access/iam["Rolle als Computeradministrator"^]
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html["Google Cloud-Berechtigungen für die NetApp Console"^]
* link:https://docs.cloud.google.com/iam/docs/roles-permissions/netapp["Google Cloud NetApp Volumes Admin"]
* link:https://docs.cloud.google.com/vmware-engine/docs/iam#vmware-engine-roles["VMware Engine-Dienstadministrator"^]




=== NetApp Console

Der NetApp Console Konsolenbenutzer muss über folgende Rollen verfügen:

* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-gcnv-roles.html["Google Cloud NetApp Volumes Administrator"^]
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html#data-service-roles["SnapCenter -Administrator"^]
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Disaster Recovery-Failover-Administrator"^]




== ONTAP -Speichervoraussetzungen

Diese Voraussetzungen gelten entweder für ONTAP oder Amazon FSX für NetApp ONTAP Instanzen.

* Quell- und Zielcluster müssen eine Peer-Beziehung haben.
* Die SVM, die die Disaster-Recovery-Volumes hostet, muss auf dem Zielcluster vorhanden sein.
* Zwischen Quell-SVM und Ziel-SVM muss eine Peer-Beziehung bestehen.
* Bei der Bereitstellung mit Amazon FSx for NetApp ONTAP gilt die folgende Voraussetzung:
+
** In Ihrer VPC muss eine Amazon FSx for NetApp ONTAP -Instanz zum Hosten von VMware DR-Datenspeichern vorhanden sein. Um loszulegen, siehelink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html["die Amazon FSx für ONTAP -Dokumentation"^] Die






== Voraussetzungen für VMware vCenter-Cluster

Diese Voraussetzungen gelten sowohl für lokale vCenter-Cluster als auch für das softwaredefinierte Rechenzentrum (SDDC) von VMware Cloud für AWS.

* Rezensionlink:../reference/vcenter-privileges.html["vCenter-Berechtigungen"] erforderlich für NetApp Disaster Recovery.
* Alle VMware-Cluster, die von NetApp Disaster Recovery verwaltet werden sollen, verwenden ONTAP Volumes zum Hosten aller VMs, die Sie schützen möchten.
* Alle VMware-Datenspeicher, die von NetApp Disaster Recovery verwaltet werden sollen, müssen eines der folgenden Protokolle verwenden:
+
** NFS
** VMFS mit dem iSCSI- oder FC-Protokoll


* VMware vSphere Version 7.0 Update 3 (7.0v3) oder höher
* Wenn Sie VMware Cloud SDDC verwenden, gelten diese Voraussetzungen.
+
** Verwenden Sie in der VMware Cloud Console die Dienstrollen „Administrator“ und „NSX Cloud-Administrator“.  Verwenden Sie den Organisationseigentümer auch für die Organisationsrolle. Siehe https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["Dokumentation zur Verwendung von VMware Cloud Foundations mit AWS FSx für NetApp ONTAP"^] .
** Verknüpfen Sie das VMware Cloud SDDC mit der Amazon FSx for NetApp ONTAP Instanz. Siehe https://vmc.techzone.vmware.com/fsx-guide#overview["VMware Cloud auf AWS-Integration mit Amazon FSx for NetApp ONTAP -Bereitstellungsinformationen"^] .






== Voraussetzungen für die NetApp Console



=== Erste Schritte mit der NetApp Console

Falls Sie dies noch nicht getan haben, https://docs.netapp.com/us-en/console-setup-admin/task-sign-up-saas.html["Melden Sie sich bei der NetApp Console an und erstellen Sie eine Organisation"^] Die



=== Sammeln Sie Anmeldeinformationen für ONTAP und VMware

* Die Anmeldeinformationen für Amazon FSx for ONTAP und AWS müssen im NetApp Console Projekt, das NetApp Disaster Recovery verwaltet, zum System hinzugefügt werden.
* Für NetApp Disaster Recovery sind vCenter-Anmeldeinformationen erforderlich.  Sie geben die vCenter-Anmeldeinformationen ein, wenn Sie eine Site in NetApp Disaster Recovery hinzufügen.
+
Eine Liste der erforderlichen vCenter-Berechtigungen finden Sie unterlink:../reference/vcenter-privileges.html["Für NetApp Disaster Recovery erforderliche vCenter-Berechtigungen"] .  Anweisungen zum Hinzufügen einer Site finden Sie unterlink:../use/sites-add.html["Hinzufügen einer Site"] .





=== Erstellen Sie den NetApp Console Agenten

Der Konsolenagent ist eine Softwarekomponente, die es der Konsole ermöglicht, mit Ihrem ONTAP Speicher und Ihren VMware vCenter-Clustern zu kommunizieren. Es ist erforderlich, damit die Notfallwiederherstellung ordnungsgemäß funktioniert. Der Agent befindet sich in Ihrem privaten Netzwerk (entweder in einem lokalen Rechenzentrum oder in einer Cloud-VPC) und kommuniziert mit Ihren ONTAP Speicherinstanzen sowie allen weiteren Server- und Anwendungskomponenten. Für die Notfallwiederherstellung ist dies der Zugriff auf Ihre verwalteten vCenter-Cluster.

In der NetApp Console muss ein Konsolenagent eingerichtet werden.  Wenn Sie den Agenten verwenden, enthält er die entsprechenden Funktionen für den Disaster Recovery-Dienst.

* NetApp Disaster Recovery funktioniert nur mit der Agent-Bereitstellung im Standardmodus. Sehen https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Erste Schritte mit der NetApp Console im Standardmodus"^] .
* Stellen Sie sicher, dass sowohl der Quell- als auch der Ziel-vCenter-Cluster denselben Console-Agenten verwenden.
* Benötigter Konsolenagenttyp:
+
** *On-Premises-zu-On-Premises-Disaster-Recovery*: Installieren Sie den On-Premises-Console-Agenten am Disaster-Recovery-Standort. Mit dieser Methode verhindert ein Ausfall des primären Standorts nicht, dass der Dienst Ihre virtuellen Ressourcen am DR-Standort neu startet. Siehe  https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-on-prem.html["Installieren und Einrichten des Konsolen-Agenten vor Ort"^].
+
Disaster Recovery unterstützt auch die Verwendung mehrerer Konsolenagenten mit lokalen Konfigurationen. In diesem Szenario leiten die Console-Agenten Aktionen an vCenter- und ONTAP -Array-Cluster weiter, wobei Quelle und Ziel jeweils über einen eigenen Console-Agenten verfügen. Es wird empfohlen, mehrere Console-Agenten zu verwenden, um die Latenz zu verringern und die Wiederherstellungszeit zu verbessern, falls ein Console-Agent oder eine Site ausfällt.

** *Vor Ort zu AWS*: Installieren Sie den Konsolenagenten für AWS in Ihrem AWS VPC. Siehe https://docs.netapp.com/us-en/console-setup-admin/concept-install-options-aws.html["Installationsoptionen für Konsolenagenten in AWS"^] .
+

TIP: Verwenden Sie für die lokale Übertragung den lokalen Konsolenagenten.  Verwenden Sie für die lokale Verbindung zu AWS den AWS-Konsolenagenten, der Zugriff auf das lokale Quell-vCenter und das lokale Ziel-vCenter hat.

** Der installierte Konsolenagent muss auf alle VMware vCenter-Clusterinstanzen und ESXi-Hosts zugreifen können, die von diesen vCenter-Clustern verwaltet werden und die von Disaster Recovery verwaltet werden.


* Alle ONTAP Arrays, die von NetApp Disaster Recovery verwaltet werden sollen, müssen zu jedem System innerhalb des NetApp Console -Projekts hinzugefügt werden, das zur Verwaltung von NetApp Disaster Recovery verwendet wird.
+
Sehen https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["Entdecken Sie lokale ONTAP -Cluster"^] .

* Informationen zum Einrichten eines intelligenten Proxys für NetApp Disaster Recovery finden Sie unterlink:../get-started/dr-setup.html["Richten Sie Ihre Infrastruktur für NetApp Disaster Recovery ein"] .




== Workload-Voraussetzungen

Um sicherzustellen, dass die Prozesse zur Anwendungskonsistenz erfolgreich sind, müssen Sie die folgenden Voraussetzungen erfüllen:

* Stellen Sie sicher, dass VMware-Tools (oder Open VM-Tools) auf den zu schützenden VMs ausgeführt werden.
* Bei Windows-VMs, auf denen Microsoft SQL Server, Oracle Database oder beides ausgeführt wird, müssen die VSS Writer der Datenbanken aktiviert sein.
* Bei Oracle-Datenbanken, die auf einem Linux-Betriebssystem laufen, muss die Betriebssystem-Benutzerauthentifizierung für die Oracle-Datenbank-SYSDBA-Rolle aktiviert sein.




== Weitere Informationen

* xref:../reference/vcenter-privileges.html[Erforderliche vCenter Privilegien]
* xref:../reference/evs-deploy-guide-config-prereqs.html[Voraussetzungen für Amazon EVS mit NetApp Disaster Recovery]

